spring:
  profiles:
    active: dev

module-properties:
  token:
    lifetimeHours: 1
  persistence:
    url: jdbc:postgresql://localhost:5433/auth
    scheme: auth
    username: auth_appl
    password: qwe123
    maxPoolSize: 5
