server:
  port: 8090

module-properties:
  token:
    lifetimeHours: 1
  auth:
    cookie:
      authCookieName: AUTH_TOKEN
      path: /
      expirationHours: 168
      secret: ru.gold.ordance
  mail:
    sender: course.paper.asu@mail.ru
    password: vXX6Aas5ErCy9ndrTVPU
    host: smtp.mail.ru
    port: 465
    protocol: smtps
    maxPoolSize: 10
  persistence:
    url: jdbc:postgresql://common-db:5432/auth
    schema: auth
    username: auth_appl
    password: qwe123
    maxPoolSize: 5
