server:
  port: 8090

module-properties:
  token:
    lifetimeHours: 1
  auth:
    cookie:
      authCookieName: AUTH_TOKEN
      path: /
      expirationHours: 168
      secret: ENC(Nwp1GvkbpkREaG2TfYF4+hH5utLBtwniEwR6Q44Kc8ec7aKeUjKX8qX7+p7FVK0I)
  mail:
    sender: course.paper.asu@mail.ru
    password: ENC(LujfrqIT9whrt7nubYds+a68HP3but12b6b3GP0LKQ/jYDDN72WLardozRg4JBm8iiXqL+0KhahcyKWgttobXw==)
    host: smtp.mail.ru
    port: 465
    protocol: smtps
    maxPoolSize: 10
  entry-failed:
    maxFailedAttempts: 7
    blockTimeMs: 900000
  persistence:
    url: jdbc:postgresql://common-db:5432/auth
    schema: auth
    username: ENC(cj8eVivlEFqzX8znKrxmrzdtfAQogOlVVLUDTQGz1mgVmDylOauzarQCD4oKaOlv)
    password: ENC(LQRO6q1enT2hcVIDTopJw0S04KSLILQUhYr5aeTbsu1wJQ0v3YEuzxQNJfwu/22m)
    maxPoolSize: 10

jasypt:
  encryptor:
    password: ${JASYPT-ENCRYPTOR-PWD}
    pool-size: 5