server:
  port: 8090

spring:
  profiles:
    active: dev

module-properties:
  token:
    lifetimeHours: 1
  mail:
    sender: course.paper.asu@mail.ru
    password: vXX6Aas5ErCy9ndrTVPU
    host: smtp.mail.ru
    port: 465
    protocol: smtps
  persistence:
    url: jdbc:postgresql://common-db:5432/auth
    scheme: auth
    username: auth_appl
    password: qwe123
    maxPoolSize: 5
