openapi: 3.0.0

info:
  title: Me components
  version: 1.0.0
paths:

components:
  schemas:
    ClientUpdateRequest:
      type: object
      properties:
        entityId:
          type: integer
          format: int64
        surname:
          type: string
        name:
          type: string
        patronymic:
          type: string
        password:
          type: string
    ClientUpdateResponse:
      type: object
      properties:
        status:
          $ref: 'common-components.yaml#/components/schemas/Status'
        object:
          $ref: 'common-components.yaml#/components/schemas/HiddenClient'
